CREATE TABLE `Cliente` (
	`ID` INTEGER AUTO_INCREMENT,
	`Nome` VARCHAR(255),
	`Endereco` VARCHAR(255),
	`Telefone` VARCHAR(20),
	`Email` VARCHAR(255),
	`Tipo_cliente` ENUM('PF', 'PJ'),
	`CPF` VARCHAR(14),
	`RG` VARCHAR(20),
	`CNPJ` VARCHAR(18),
	PRIMARY KEY(`ID`)
);


CREATE TABLE `Editora` (
	`ID` INTEGER AUTO_INCREMENT,
	`Nome` VARCHAR(255),
	`Telefone` VARCHAR(20),
	`Email` VARCHAR(255),
	PRIMARY KEY(`ID`)
);


CREATE TABLE `Livro` (
	`ID` INTEGER AUTO_INCREMENT,
	`Titulo` VARCHAR(255),
	`Categoria` VARCHAR(100),
	`ISBN` VARCHAR(20),
	`Ano_Publicacao` YEAR,
	`Valor` DECIMAL,
	`Editora_ID` INTEGER,
	PRIMARY KEY(`ID`)
);


CREATE TABLE `Estoque` (
	`ID` INTEGER AUTO_INCREMENT,
	`Livro_ID` INTEGER,
	`Quantidade` INTEGER,
	`Cod_Editora` INTEGER,
	PRIMARY KEY(`ID`)
);


CREATE TABLE `Pedido` (
	`ID` INTEGER AUTO_INCREMENT,
	`Cliente_ID` INTEGER,
	`Data_Pedido` DATE,
	`Valor` DECIMAL,
	PRIMARY KEY(`ID`)
);


CREATE TABLE `Item_Pedido` (
	`Pedido_ID` INTEGER,
	`Livro_ID` INTEGER,
	`Quantidade` INTEGER,
	PRIMARY KEY(`Pedido_ID`, `Livro_ID`)
);


ALTER TABLE `Livro`
ADD FOREIGN KEY(`Editora_ID`) REFERENCES `Editora`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Estoque`
ADD FOREIGN KEY(`Livro_ID`) REFERENCES `Livro`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Estoque`
ADD FOREIGN KEY(`Cod_Editora`) REFERENCES `Editora`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Pedido`
ADD FOREIGN KEY(`Cliente_ID`) REFERENCES `Cliente`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Item_Pedido`
ADD FOREIGN KEY(`Pedido_ID`) REFERENCES `Pedido`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Item_Pedido`
ADD FOREIGN KEY(`Livro_ID`) REFERENCES `Livro`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;